name: Run BigTesty Test

env:
  GOOGLE_PROJECT: gb-poc-373711
  GOOGLE_REGION: europe-west1
  PULUMI_BACKEND_URL: gs://gb-poc-pulumi-state/bigtesty
  BIGTESTY_STACK_NAME: bigtesty
  PULUMI_CONFIG_PASSPHRASE: gcp_fake_passphrase

  WORKLOAD_IDENTITY_PROVIDER: 'projects/975119474255/locations/global/workloadIdentityPools/gb-github-actions-ci-cd-pool/providers/gb-github-actions-ci-cd-provider'
  SA_CI_CD_EMAIL: 'sa-bigtesty@gb-poc-373711.iam.gserviceaccount.com'

on:
  workflow_dispatch:

jobs:
  run-template:

    runs-on: ubuntu-latest
    container: mazlumtosun/bigtesty

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ env.SA_CI_CD_EMAIL }}'

      - name: 'Run BigTesty Tests'
        run: |
          bigtesty test \
          --root-test-folder $GITHUB_WORKSPACE/tests \
          --root-tables-folder $GITHUB_WORKSPACE/tests/tables \
          --tables-config-file $GITHUB_WORKSPACE/tests/tables/tables.json